swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
       #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
# Transaction
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: all transactions for current month
      description: API for fetching current month transactions
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Attach Bearer JWT token
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
          examples:
            application/json:
              - id: 1
                amount: 100.0
                date: '2023-10-01'
                description: 'Grocery shopping'
              - id: 2
                amount: 50.0
                date: '2023-10-02'
                description: 'Gas station'
        '400':
          description: Invalid Fields
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Invalid request parameters"
              code: 400
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Unauthorized access"
              code: 401
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Access forbidden"
              code: 403
        '404':
          description: Transactions not found
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Transactions not found"
              code: 404
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Internal server error"
              code: 500
  /user/transactions/{id}:
    # Paramètre d'URL pour identifier une transaction spécifique
    parameters:
      - in: path
        name: id
        description: Id of the transaction
        required: true
        type: string
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: details of a transaction
      description: API to show a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Transaction'
          examples:
            application/json:
              id: 1
              amount: 100.0
              date: '2023-10-01'
              description: 'Grocery shopping'
        '400':
          description: Invalid Field
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Invalid request parameters"
              code: 400
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Unauthorized access"
              code: 401
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Access forbidden"
              code: 403
        '404':
          description: Transactions not found
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Transaction not found"
              code: 404
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Internal server error"
              code: 500
  /user/transactions/{id}/category:
  # Paramètre de chemin pour identifier la transaction à modifier
    parameters:
      - in: path
        name: id
        description: Transaction category
        required: true
        type: string
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: update transaction information (category)
      description: API to modify a transaction's category
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          required: true
          description: Update transaction's informations
          schema:
            $ref: '#/definitions/TransactionsUpdateCategory'
      responses:
        '200':
          description: transaction patched successfully
        '400':
          description: Invalid Fields
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Invalid request parameters"
              code: 400
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Unauthorized access"
              code: 401
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Access forbidden"
              code: 403
        '404':
          description: Transactions not found
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Transaction not found"
              code: 404
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Internal server error"
              code: 500
  /user/transactions/{id}/note:
     # Paramètre de chemin pour identifier la transaction à laquelle ajouter une note
    parameters:
      - in: path
        name: id
        description: Transaction note
        required: true
        type: string
    patch:
      tags:
        - Transactions
      summary: add transaction information (note)
      description: API to add a transaction
      parameters:
        - in: body
          name: body
          description: Transaction details
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: transaction added successfully
        '400':
          description: Invalid Fields
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Invalid request parameters"
              code: 400
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Unauthorized access"
              code: 401
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Access forbidden"
              code: 403
        '404':
          description: Transactions not found
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Transaction not found"
              code: 404
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              message: "Internal server error"
              code: 500

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  TransactionsUpdateCategory:
    type: object
    properties:
      category:
        type: string
        example: Groceries
  Transaction:
    type: object
    properties:
      note:
        type: string
        example: Dinner at restaurant
  ErrorResponse:
    type: object
    properties:
      message:
        type: string
        example: "Error message"
      code:
        type: integer
        example: 400
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header